getname();
// getnamenew acts as variabler so it will through error
// getnameNew();
console.log(x);
var x = 7;

function getname() {
  console.log("keshav");
}

const getnameNew = () => {
  console.log("keshav new");
};

console.log("doown the code");
getname();
getnameNew();
console.log(x);
console.log(getname);
console.log(getnameNew);
